spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/gestion_stock
    username: postgres
    password: root
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    hibernate:
      ddl-auto: update
  jackson:
    serialization:
      write-dates-as-timestamps: false
    deserialization:
      accept-single-value-as-array: true

server:
  port: 8081
